### ISSUE TITLE
Add custom require-like option

### ISSUE THREAD

**Issue by supernghia89** [operali/vscode-lua-booster#1]
Please add the custom require-like option
![image](https://user-images.githubusercontent.com/15607260/176983888-7f311ad4-5d37-4489-9594-c6cf4df6ee49.png)
Thanks

**Comment by operali** [comment]
we provided this feature, referent to FAQ:

Q: 2. our project use Module instead of `require`
A:
a) ctrl + shift + p open the command box
b) Type in `lua booster setting`
c) choose module
d) add a procedure for load
...

**Comment by supernghia89** [comment]
> 

It worked !!!

Another question, Is possible to setup it in global

Thank you

**Comment by operali** [comment]
it currently could be set for the project/working folder, we think there are different `require`  in different project/folders in most cases.

for instance, people use standards `require` for simple Lua script, and other module system in the project at the same time
